CREATE DATABASE IF NOT EXISTS Draculotto;
USE Draculotto;

CREATE TABLE IF NOT EXISTS reference_numbers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    input_number VARCHAR(2) NOT NULL,
    output_number1 VARCHAR(2) NOT NULL,
    output_number2 VARCHAR(2) NOT NULL,
    output_number3 VARCHAR(2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
